// Code generated by MockGen. DO NOT EDIT.
// Source: client.go
//
// Generated by this command:
//
//	mockgen -destination /Users/subramk/source/github.com/unmeshjoshi/gokube/mocks/pkg/sdk/client.go -package sdk -source client.go
//

// Package sdk is a generated GoMock package.
package sdk

import (
	sdk "gokube/pkg/sdk"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockClientInterface is a mock of ClientInterface interface.
type MockClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockClientInterfaceMockRecorder
	isgomock struct{}
}

// MockClientInterfaceMockRecorder is the mock recorder for MockClientInterface.
type MockClientInterfaceMockRecorder struct {
	mock *MockClientInterface
}

// NewMockClientInterface creates a new mock instance.
func NewMockClientInterface(ctrl *gomock.Controller) *MockClientInterface {
	mock := &MockClientInterface{ctrl: ctrl}
	mock.recorder = &MockClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientInterface) EXPECT() *MockClientInterfaceMockRecorder {
	return m.recorder
}

// Nodes mocks base method.
func (m *MockClientInterface) Nodes() sdk.NodeInterface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Nodes")
	ret0, _ := ret[0].(sdk.NodeInterface)
	return ret0
}

// Nodes indicates an expected call of Nodes.
func (mr *MockClientInterfaceMockRecorder) Nodes() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Nodes", reflect.TypeOf((*MockClientInterface)(nil).Nodes))
}

// Pods mocks base method.
func (m *MockClientInterface) Pods() sdk.PodInterface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Pods")
	ret0, _ := ret[0].(sdk.PodInterface)
	return ret0
}

// Pods indicates an expected call of Pods.
func (mr *MockClientInterfaceMockRecorder) Pods() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Pods", reflect.TypeOf((*MockClientInterface)(nil).Pods))
}

// ReplicaSets mocks base method.
func (m *MockClientInterface) ReplicaSets() sdk.ReplicaSetInterface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplicaSets")
	ret0, _ := ret[0].(sdk.ReplicaSetInterface)
	return ret0
}

// ReplicaSets indicates an expected call of ReplicaSets.
func (mr *MockClientInterfaceMockRecorder) ReplicaSets() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplicaSets", reflect.TypeOf((*MockClientInterface)(nil).ReplicaSets))
}
