// Code generated by MockGen. DO NOT EDIT.
// Source: pod.go
//
// Generated by this command:
//
//	mockgen -destination /Users/subramk/source/github.com/unmeshjoshi/gokube/mocks/pkg/sdk/pod.go -package sdk -source pod.go
//

// Package sdk is a generated GoMock package.
package sdk

import (
	context "context"
	api "gokube/pkg/api"
	sdk "gokube/pkg/sdk"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPodInterface is a mock of PodInterface interface.
type MockPodInterface struct {
	ctrl     *gomock.Controller
	recorder *MockPodInterfaceMockRecorder
	isgomock struct{}
}

// MockPodInterfaceMockRecorder is the mock recorder for MockPodInterface.
type MockPodInterfaceMockRecorder struct {
	mock *MockPodInterface
}

// NewMockPodInterface creates a new mock instance.
func NewMockPodInterface(ctrl *gomock.Controller) *MockPodInterface {
	mock := &MockPodInterface{ctrl: ctrl}
	mock.recorder = &MockPodInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPodInterface) EXPECT() *MockPodInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPodInterface) Create(ctx context.Context, pod *api.Pod) (*api.Pod, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, pod)
	ret0, _ := ret[0].(*api.Pod)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockPodInterfaceMockRecorder) Create(ctx, pod any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPodInterface)(nil).Create), ctx, pod)
}

// Delete mocks base method.
func (m *MockPodInterface) Delete(ctx context.Context, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockPodInterfaceMockRecorder) Delete(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPodInterface)(nil).Delete), ctx, name)
}

// Get mocks base method.
func (m *MockPodInterface) Get(ctx context.Context, name string) (*api.Pod, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, name)
	ret0, _ := ret[0].(*api.Pod)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockPodInterfaceMockRecorder) Get(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockPodInterface)(nil).Get), ctx, name)
}

// List mocks base method.
func (m *MockPodInterface) List(ctx context.Context, opts ...sdk.ListOption) ([]*api.Pod, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "List", varargs...)
	ret0, _ := ret[0].([]*api.Pod)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockPodInterfaceMockRecorder) List(ctx any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockPodInterface)(nil).List), varargs...)
}

// ListUnassigned mocks base method.
func (m *MockPodInterface) ListUnassigned(ctx context.Context) ([]*api.Pod, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUnassigned", ctx)
	ret0, _ := ret[0].([]*api.Pod)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUnassigned indicates an expected call of ListUnassigned.
func (mr *MockPodInterfaceMockRecorder) ListUnassigned(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUnassigned", reflect.TypeOf((*MockPodInterface)(nil).ListUnassigned), ctx)
}

// Update mocks base method.
func (m *MockPodInterface) Update(ctx context.Context, pod *api.Pod) (*api.Pod, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, pod)
	ret0, _ := ret[0].(*api.Pod)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockPodInterfaceMockRecorder) Update(ctx, pod any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockPodInterface)(nil).Update), ctx, pod)
}
