// Code generated by MockGen. DO NOT EDIT.
// Source: replicaset.go
//
// Generated by this command:
//
//	mockgen -destination /Users/subramk/source/github.com/unmeshjoshi/gokube/mocks/pkg/sdk/replicaset.go -package sdk -source replicaset.go
//

// Package sdk is a generated GoMock package.
package sdk

import (
	context "context"
	api "gokube/pkg/api"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockReplicaSetInterface is a mock of ReplicaSetInterface interface.
type MockReplicaSetInterface struct {
	ctrl     *gomock.Controller
	recorder *MockReplicaSetInterfaceMockRecorder
	isgomock struct{}
}

// MockReplicaSetInterfaceMockRecorder is the mock recorder for MockReplicaSetInterface.
type MockReplicaSetInterfaceMockRecorder struct {
	mock *MockReplicaSetInterface
}

// NewMockReplicaSetInterface creates a new mock instance.
func NewMockReplicaSetInterface(ctrl *gomock.Controller) *MockReplicaSetInterface {
	mock := &MockReplicaSetInterface{ctrl: ctrl}
	mock.recorder = &MockReplicaSetInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReplicaSetInterface) EXPECT() *MockReplicaSetInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockReplicaSetInterface) Create(ctx context.Context, replicaset *api.ReplicaSet) (*api.ReplicaSet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, replicaset)
	ret0, _ := ret[0].(*api.ReplicaSet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockReplicaSetInterfaceMockRecorder) Create(ctx, replicaset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockReplicaSetInterface)(nil).Create), ctx, replicaset)
}

// Delete mocks base method.
func (m *MockReplicaSetInterface) Delete(ctx context.Context, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockReplicaSetInterfaceMockRecorder) Delete(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockReplicaSetInterface)(nil).Delete), ctx, name)
}

// Get mocks base method.
func (m *MockReplicaSetInterface) Get(ctx context.Context, name string) (*api.ReplicaSet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, name)
	ret0, _ := ret[0].(*api.ReplicaSet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockReplicaSetInterfaceMockRecorder) Get(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockReplicaSetInterface)(nil).Get), ctx, name)
}

// List mocks base method.
func (m *MockReplicaSetInterface) List(ctx context.Context) ([]*api.ReplicaSet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]*api.ReplicaSet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockReplicaSetInterfaceMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockReplicaSetInterface)(nil).List), ctx)
}

// Update mocks base method.
func (m *MockReplicaSetInterface) Update(ctx context.Context, replicaset *api.ReplicaSet) (*api.ReplicaSet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, replicaset)
	ret0, _ := ret[0].(*api.ReplicaSet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockReplicaSetInterfaceMockRecorder) Update(ctx, replicaset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockReplicaSetInterface)(nil).Update), ctx, replicaset)
}
